info:
  namespace: builderslab
  dictionary-lang: "en"
dictionary:
  # tools
  display-name-block_puncher: "Block puncher"
  lore-block_puncher: "&7Click on a block to push it"
  display-name-wrench: "Wrench"
  lore-wrench: "&7Click on a block to rotate it"
  display-name-trowel: "Trowel"
  lore-1-trowel: "&7Click to place a random block"
  lore-2-trowel: "&7from the hotbar"
  display-name-chisel: "Chisel"
  lore-1-chisel: "&7Left click to replace the block"
  lore-2-chisel: "&7with the one on the offhand"
  display-name-carpenter_hammer: "Carpenter hammer"
  lore-1-carpenter_hammer: "&7Click on an armor stand"
  lore-2-carpenter_hammer: "&7to change its pose"
  display-name-sickle: "Sickle"
  lore-sickle: "&7Harvests crops in a 3x3 area"
  # items
  display-name-hello_world_stick: "Hello world"
  lore-hello_world_stick: "&7Click to say hello to the world"
  display-name-skeleton_crown: "Skeleton crown"
  lore-1-skeleton_crown: "&7Build a Skeleton Totem and place"
  lore-2-skeleton_crown: "&7this crown over the skull to"
  lore-3-skeleton_crown: "&7summon a Skeleton king"
  display-name-slime_egg: "Slime egg"
  lore-slime_egg: "&7Click to summon a slime"
  display-name-experience_book: "Experience Book"
  lore-1-experience_book: "&7Click to store levels in this book"
  lore-2-experience_book: "&7Click on a bookshelf to retrieve all levels"
  display-name-mineralized_pile: "Mineralized pile"
  lore-mineralized_pile: "&7Drop it on water and see what contains"
  display-name-enriched_bone_meal: "Enriched bone meal"
  lore-enriched_bone_meal: "&7Click on a dirt block to spread grass"
  # hanging_item_frame
  display-name-hanging_item_frame: "Hanging item frame"
  lore-hanging_item_frame: "&7Left click on a hanging sign to place it"
  # rack
  display-name-oak_rack: "Oak rack"
  display-name-spruce_rack: "Spruce rack"
  display-name-birch_rack: "Birch rack"
  display-name-jungle_rack: "Jungle rack"
  display-name-acacia_rack: "Acacia rack"
  display-name-dark_oak_rack: "Dark oak rack"
  display-name-mangrove_rack: "Mangrove rack"
  display-name-cherry_rack: "Cherry rack"
  display-name-pale_oak_rack: "Pale oak rack"
  display-name-bamboo_rack: "Bamboo rack"
  display-name-crimson_rack: "Crimson rack"
  display-name-warped_rack: "Warped rack"
  # wall_rack
  display-name-oak_wall_rack: "Oak wall rack"
  display-name-spruce_wall_rack: "Spruce wall rack"
  display-name-birch_wall_rack: "Birch wall rack"
  display-name-jungle_wall_rack: "Jungle wall rack"
  display-name-acacia_wall_rack: "Acacia wall rack"
  display-name-dark_oak_wall_rack: "Dark oak wall rack"
  display-name-mangrove_wall_rack: "Mangrove wall rack"
  display-name-cherry_wall_rack: "Cherry wall rack"
  display-name-pale_oak_wall_rack: "Pale oak wall rack"
  display-name-bamboo_wall_rack: "Bamboo wall rack"
  display-name-crimson_wall_rack: "Crimson wall rack"
  display-name-warped_wall_rack: "Warped wall rack"
  # categories
  display-category-tools: "Builder's Lab Tools"
  display-category-items: "Builder's Lab Items"
  display-category-furniture: "Builder's Lab Furniture"