info:
  namespace: builderslab
  dictionary-lang: "es"
dictionary:
  # tools
  display-name-block_puncher: "Golpeador de bloques"
  lore-block_puncher: "&7Clic en un bloque para empujarlo"
  display-name-wrench: "Llave inglesa"
  lore-wrench: "&7Clic en un bloque para rotarlo"
  display-name-trowel: "Paleta de albañil"
  lore-1-trowel: "&7Clic para colocar un bloque aleatorio"
  lore-2-trowel: "&7desde la hotbar"
  display-name-chisel: "Cincel"
  lore-1-chisel: "&7Clic izquierdo para reemplazar el bloque"
  lore-2-chisel: "&7por el que tienes en la mano secundaria"
  display-name-carpenter_hammer: "Martillo de carpintero"
  lore-1-carpenter_hammer: "&7Clic en un soporte para armadura"
  lore-2-carpenter_hammer: "&7para cambiar su pose"
  display-name-sickle: "Hoz"
  lore-sickle: "&7Cosecha cultivos en un área de 3x3"
  # items
  display-name-hello_world_stick: "Hola mundo"
  lore-hello_world_stick: "&7Clic para saludar al mundo"
  display-name-skeleton_crown: "Corona de esqueleto"
  lore-1-skeleton_crown: "&7Construye un tótem de esqueleto y coloca"
  lore-2-skeleton_crown: "&7esta corona sobre la calavera para"
  lore-3-skeleton_crown: "&7invocar al rey esqueleto"
  display-name-slime_egg: "Huevo de slime"
  lore-slime_egg: "&7Clic para generar un slime"
  display-name-experience_book: "Libro de experiencia"
  lore-1-experience_book: "&7Clic para almacenar niveles en este libro"
  lore-2-experience_book: "&7Clic en una estantería para recuperar todos los niveles"
  display-name-grapling_hook: "Gancho"
  lore-grapling_hook: "&7Clic derecho para lanzar el gancho"
  display-name-mineralized_pile: "Pila mineralizada"
  lore-mineralized_pile: "&7Sueltalo en el agua y descubre su contenido"
  display-name-enriched_bone_meal: "Polvo de hueso enriquecido"
  lore-enriched_bone_meal: "&7Clic en un bloque de tierra para extender césped"
  # hanging_item_frame
  display-name-hanging_item_frame: "Marco colgante"
  lore-hanging_item_frame: "&7Clic izquierdo en un cartel colgante para colocarlo"
  # rack
  display-name-oak_rack: "Soporte de roble"
  display-name-spruce_rack: "Soporte de abeto"
  display-name-birch_rack: "Soporte de abedul"
  display-name-jungle_rack: "Soporte de jungla"
  display-name-acacia_rack: "Soporte de acacia"
  display-name-dark_oak_rack: "Soporte de roble oscuro"
  display-name-mangrove_rack: "Soporte de mangle"
  display-name-cherry_rack: "Soporte de cerezo"
  display-name-pale_oak_rack: "Soporte de roble pálido"
  display-name-bamboo_rack: "Soporte de bambú"
  display-name-crimson_rack: "Soporte carmesí"
  display-name-warped_rack: "Soporte distorsionado"
  # wall_rack
  display-name-oak_wall_rack: "Soporte de pared de roble"
  display-name-spruce_wall_rack: "Soporte de pared de abeto"
  display-name-birch_wall_rack: "Soporte de pared de abedul"
  display-name-jungle_wall_rack: "Soporte de pared de jungla"
  display-name-acacia_wall_rack: "Soporte de pared de acacia"
  display-name-dark_oak_wall_rack: "Soporte de pared de roble oscuro"
  display-name-mangrove_wall_rack: "Soporte de pared de mangle"
  display-name-cherry_wall_rack: "Soporte de pared de cerezo"
  display-name-pale_oak_wall_rack: "Soporte de pared de roble pálido"
  display-name-bamboo_wall_rack: "Soporte de pared de bambú"
  display-name-crimson_wall_rack: "Soporte de pared carmesí"
  display-name-warped_wall_rack: "Soporte de pared distorsionado"
  # categories
  display-category-tools: "Herramientas de Builder's Lab"
  display-category-items: "Objetos de Builder's Lab"
  display-category-furniture: "Muebles de Builder's Lab"